### ISSUE TITLE
Update docs to use the term "Confluent Cloud" correctly 

### ISSUE THREAD

**Issue by programmiri** [Aiven-Open/klaw-docs#100]
# Description

"Confluent Cloud" should always be written in that way.

Occurrences of other usages (e.g. just "Confluent cloud" should be replaced with the correct one. 

In order to help find occurrences, we added a style rule in our Vale config (`branding-temp.xml`)

## Todo:

- cut and past the line related to Confluent Cloud(`"(?i)Confluent Cloud"`) from our temporary branding-warning config and add it to `branding.yaml`

- run `npm run spell:error`

This will give you a report of errors and help you find occurrences of the wrong use in the text.

The log will show you the file where the word was found as well as the line number:

<img width="713" alt="Screenshot 2023-09-28 at 13 17 04" src="https://github.com/Aiven-Open/klaw-docs/assets/943800/76b45249-c9c7-43a7-9b6f-97e4d091a872">

- update the usage to correct branding in text in markdown files

The `npm run spell:error` should be green before making a PR.

**Comment by Rawshansharma** [comment]
can i work on this issue ?

**Comment by csengineer1990** [comment]
Hi @programmiri  I am participating for the first time in Hacktoberfest and I want to contribute to this issue. can I help here to update the doc?

**Comment by programmiri** [comment]
Hi @csengineer1990  I'll assign you. Thank you 🎉  Please feel free to reach out if you have questions :)

**Comment by csengineer1990** [comment]
@programmiri Thank you so much.

**Comment by csengineer1990** [comment]
Hi @programmiri I made the changes in the changes from branding-warning-temp.yml into branding.yml and I haven't changed in confluent-cloud-kafka-cluster-ssl-protocol.md file but i getting output as below screenshot after running "npm run spell:error".

Please check and let me know if I am wrong or if I did anything wrong. Please guide me.

![klawError](https://github.com/Aiven-Open/klaw-docs/assets/68468678/a5bee5bf-2316-402c-80d2-bc67985d2a57)

**Comment by programmiri** [comment]
Hi @csengineer1990, I'm sorry, that is my bad! The rule I added to the example is not correct. 

It should be: 
`"(?i)Confluent[ -]?Cloud": Confluent Cloud`

This will make sure to match case-insensitive and also e.g. match something like `ConfluentCloud` (which I don't think we have somewhere).

**Comment by csengineer1990** [comment]
HI @programmiri it's ok mam. 
Now I have to paste "(?i)Confluent[ -]?Cloud": Confluent Cloud in the branding.yml file right?
And remove this old "(?i)Confluent Cloud": Confluent Cloud from the branding-warning-temp.yml file right?
please help.

**Comment by programmiri** [comment]
> Now I have to paste "(?i)Confluent[ -]?Cloud": Confluent Cloud in the branding.yml file right?
> And remove this old "(?i)Confluent Cloud": Confluent Cloud from the branding-warning-temp.yml file right?

Exactly! 

So, in the end, ` branding.yml` will have one rule related to Confluent Cloud -> ` "(?i)Confluent[ -]?Cloud"`
and `branding-warning-temp.yml` will not have any rule related to Confluent Cloud. 

That way, we make sure that a wrong spelling like e.g. "Confluent cloud" will in future be flagged as an error.

**Comment by csengineer1990** [comment]
ok mam, The above changes I made in the file but when I try to run "npm run spell: error" I do not get any error if try to find it with the "ConfluentCloud " word. Why is that?

**Comment by csengineer1990** [comment]
Thank you so much.
