### ISSUE TITLE
Update docs to use the term "API" correctly

### ISSUE THREAD

**Issue by programmiri** [Aiven-Open/klaw-docs#101]
# Description

"API" should always be capitalised.

Occurrences of other usages (e.g. just "Api" or "api" etc. should be replaced with the correct one. 

In order to help find occurrences, we added a style rule in our Vale config (`branding-temp.xml`)

## Todo:

- cut and past the line related to API (`"(?i)api"`) from our temporary branding-warning config and add it to `branding.yaml`

- run `npm run spell:error`

This will give you a report of errors and help you find occurrences of the wrong use in the text.

The log will show you the file where the word was found as well as the line number:

<img width="513" alt="Screenshot 2023-09-28 at 13 18 21" src="https://github.com/Aiven-Open/klaw-docs/assets/943800/87d5f789-03c0-4c49-8ec9-d53fe2aea922">

- update the usage to correct branding in text in markdown files

The `npm run spell:error` should be green before making a PR.

**Comment by WangGithub0** [comment]
Hi @programmiri, could I work on this issue? thanks

**Comment by programmiri** [comment]
Hi @WangGithub0  I assigned you! Thank you 🎉  Please feel free to reach out if you have questions!
