### ISSUE TITLE
Update docs to use the term "Kafka Connect" correctly

### ISSUE THREAD

**Issue by programmiri** [Aiven-Open/klaw-docs#102]
# Description

"Kafka Connect" should always be written capitalised.

Occurrences of other usages (e.g. just "Kafka connect" should be replaced with the correct one. 

In order to help find occurrences, we added a style rule in our Vale config (`branding-temp.xml`)

## Todo:

- cut and past the line related to Kafka Connect (`"(?i)kafka connect"`) from our temporary branding-warning config and add it to `branding.yaml`

- run `npm run spell:error`

This will give you a report of errors and help you find occurrences of the wrong use in the text.

The log will show you the file where the word was found as well as the line number:

<img width="592" alt="Screenshot 2023-09-28 at 13 20 26" src="https://github.com/Aiven-Open/klaw-docs/assets/943800/ebd0d02b-58c7-439f-9e41-65361d833dbf">

- update the usage to correct branding in text in markdown files
- Bonus: If you find usages of "connect" where it's clearly related to the Kafka Connect, you can replace those, too 

The `npm run spell:error` should be green before making a PR.

**Comment by Rawshansharma** [comment]
can I work on this issue?

**Comment by programmiri** [comment]
@Rawshansharma  sure! I'll assign you. Thanks 🎉
