### ISSUE TITLE
Update docs to use the term "Klaw Core" correctly

### ISSUE THREAD

**Issue by programmiri** [Aiven-Open/klaw-docs#103]
# Description

"Klaw Core" should always be written capitalised.

Occurrences of other usages (e.g. just ""Klaw core" should be replaced with the correct one. 

In order to help find occurrences, we added a style rule in our Vale config (`branding-temp.xml`)

## Todo:

- cut and past the line related to "Klaw Core (`(?i)klaw core`) from our temporary branding-warning config and add it to `branding.yaml`

- run `npm run spell:error`

This will give you a report of errors and help you find occurrences of the wrong use in the text.

The log will show you the file where the word was found as well as the line number:

<img width="571" alt="Screenshot 2023-09-28 at 13 22 50" src="https://github.com/Aiven-Open/klaw-docs/assets/943800/b700459f-ae3f-4704-b2cd-ed97f6d93c01">

- update the usage to correct branding in text in markdown files

- Bonus: If you find usages of "core" where it's clearly related to the Klaw Core, you can replace those, too 

The `npm run spell:error` should be green before making a PR.

**Comment by morgoth9808** [comment]
I want to work on this issue

**Comment by Rawshansharma** [comment]
can I work on this issue?

**Comment by programmiri** [comment]
Hi @morgoth9808  - We already have a PR for this issue, but I've already assigned you to another issue you asked about.

**Comment by programmiri** [comment]
This issue is open again for Hacktoberfest 🎃
