### ISSUE TITLE
Update docs to use the term "Klaw" correctly

### ISSUE THREAD

**Issue by programmiri** [Aiven-Open/klaw-docs#104]
# Description

"Klaw" should always be written capitalised.

Occurrences of other usages (e.g. "klaw" should be replaced with the correct one. 

In order to help find occurrences, we added a style rule in our Vale config (`branding-temp.xml`)

## Todo:

- cut and past the line related to Klaw (`"(?i)klaw"`) from our temporary branding-warning config and add it to `branding.yaml`

- run `npm run spell:error`

This will give you a report of errors and help you find occurrences of the wrong use in the text.

The log will show you the file where the word was found as well as the line number:

<img width="708" alt="Screenshot 2023-09-28 at 13 26 44" src="https://github.com/Aiven-Open/klaw-docs/assets/943800/a5898430-96ab-4e44-b6f7-ed88e0e4634d">

- update the usage to correct branding in text in markdown files

The `npm run spell:error` should be green before making a PR.

**Comment by Basavarajakjbasuu** [comment]
Its  my grate privilege to onboard my journey in Open source contribution, I will work on this issue

**Comment by Basavarajakjbasuu** [comment]
Thank you for assigning the issue to me. I appreciate the opportunity to contribute to our repository and make it more accessible for contributors.

I setup this repo locally and  as of my knowledge I fixed this issue also but When I performing commit I getting This error.
Could you please help me:)

```bash
🙋 Check "lint-staged" in failed.
   Canceling the commit process.
   Please fix and try again!


   To fix formatting, run: npm run reformat
   ```

   and I ran command: npm run reformat also still facing same issue

**Comment by programmiri** [comment]
OK, let's see if we can figure this out together :) 

- did you add the changes after running `npm run reformat`?  
I sometimes forget that, but the pre-commit hook will only check for files that are staged for the commit.


- Could you check which job fails? We use `markdown-lint` and the issues this linter finds can't be automatically formatted with `npm run reformat`. 

It would look like this:

<img width="739" alt="Screenshot 2023-09-28 at 16 20 28" src="https://github.com/Aiven-Open/klaw-docs/assets/943800/eb91e157-0f08-4c51-b091-6055f80ff38f">

**Comment by programmiri** [comment]
Sorry, I was not clear enough in my previous message 🙈 

Did you run `git add .` after you run `npm run reformat`? 

It looks like the issue was caused by prettier & those issues should all be fixed by running reformat, but the pre-commit hook will only check for files that are added to be comitted. 

You can also push your changes to your fork without running the pre-commit hook, by doing `git commit -s --no-verify`. Then I can take a loot at it :)

**Comment by Basavarajakjbasuu** [comment]
Yes I ran ```git add  . ``` after ran ``` npm run reformate``` but still facing same issue.

I pushed my code to my forked repo. Can I Raise PR?

**Comment by programmiri** [comment]
Thanks! 

As far as I can see, there should be nothing wrong with linting. 

Let's see what our pipeline says!

Can you:
- remove the files `package.json` and `package-lock.json` from your branch 
- create a pull request

Then our GitHub pipeline will run all checks and we can see if the issue you encountered was maybe something locally caused.

**Comment by Basavarajakjbasuu** [comment]
I have made a PR on this issue Please let me know  for further clarification
