### ISSUE TITLE
Update docs to use the term "SSL" correctly 

### ISSUE THREAD

**Issue by programmiri** [Aiven-Open/klaw-docs#105]
# Description

"SSL" should always be written capitalised.

Occurrences of other usages (e.g. "ssl") should be replaced with the correct one. 

In order to help find occurrences, we added a style rule in our Vale config (`branding-temp.xml`)

## Todo:

- cut and past the line related to SSL (`"(?i)ssl"`) from our temporary branding-warning config and add it to `branding.yaml`

- run `npm run spell:error`

This will give you a report of errors and help you find occurrences of the wrong use in the text.

The log will show you the file where the word was found as well as the line number:

<img width="585" alt="Screenshot 2023-09-28 at 13 33 27" src="https://github.com/Aiven-Open/klaw-docs/assets/943800/a25b4a55-cf14-4f7a-98b1-f8ea79def082">

- update the usage to correct branding in text in markdown files

The `npm run spell:error` should be green before making a PR.

**Comment by Devrishi-Dutta** [comment]
can I work on this issue?

**Comment by programmiri** [comment]
Hi @Devrishi-Dutta, yes, of course, we appreciate it 🎉  I'll assign you. 

Please feel free to reach out if you have any questions!

**Comment by Devrishi-Dutta** [comment]
Do I have to modify the filenames and links as well ?

**Comment by Devrishi-Dutta** [comment]
can you give an example of Link to SSL provider ?

**Comment by Devrishi-Dutta** [comment]
like do I need to modify this? ->  server.ssl.key-store.*

**Comment by Devrishi-Dutta** [comment]
I made a PR for this issue , plz let me know if am still missing any ssl.

**Comment by programmiri** [comment]
Done with #112
