### ISSUE TITLE
Update correct usage of copyright for Apache Kafka

### ISSUE THREAD

**Issue by programmiri** [Aiven-Open/klaw-docs#106]
⚠️ Wait for #98  to be merged

# Description

The first occurrence of the name "Apacha Kafka" on a page always has to have a copyright (`Apache Kafka®`)

In order to help find occurrences, we added a style rule in our Vale config (`first-kafka-registered.yml`)

## Todo:

- in the Vale style config, set the level to "error" (`level: error`)

- run `npm run spell:error`

This will give you a report of errors and help you find occurrences of the wrong use in the text.

The log will show you the file where the first use of it was found without a trademark as well as the line number:
<img width="696" alt="Screenshot 2023-09-28 at 13 40 23" src="https://github.com/Aiven-Open/klaw-docs/assets/943800/fb7fae13-d751-44ef-b62e-64ee9fc718ba">

Note:  The error will list all findings for the use of "Kafka" without the trademark. You need to add the `®` to the **first**  occurrence on the page. 

- update the usage to correct trademarking 

The `npm run spell:error` should be green before making a PR.

**Comment by Basavarajakjbasuu** [comment]
Hey @programmiri Can I work on this issue🦸.

**Comment by programmiri** [comment]
Hi @Basavarajakjbasuu  of course :) I'll assign you! Thank you 🎉

**Comment by Basavarajakjbasuu** [comment]
Could you please clarify, I need to modify only ```Apache Kafka``` to ```Apache Kafka®``` or both ```Kafka``` to ```Kafka®```

**Comment by programmiri** [comment]
Sure! 

The rule that you're working on will check that we always have the first mention of "Kafka" with the trademark. 

We have another issue that someone is working on that will check that "Kafka" is never used alone, but always as "Apache Kafka". 

So for you that means you will add `®` to the first mention of "Kafka" in a document (not only "Apache Kafka"). 

If you want to do a bit more :D you can also add the "Apache" before the "Kafka" you're adding the trademark to. But that's not required for this PR.

**Comment by programmiri** [comment]
This issue is open again for Hacktoberfest 🎃
