### ISSUE TITLE
Update correct usage of copyright for PostgreSQL

### ISSUE THREAD

**Issue by programmiri** [Aiven-Open/klaw-docs#109]
# Description

The first occurrence of the name "PostgreSQL" on a page always has to have a copyright (`PostgreSQL®`)

In order to help find occurrences, we added a style rule in our Vale config (`first-postgresql-registered.yml`)

## Todo:

- in the Vale style config, set the level to "error" (`level: error`)

- run `npm run spell:error`

This will give you a report of errors and help you find occurrences of the wrong use in the text.

<img width="785" alt="Screenshot 2023-09-28 at 15 36 39" src="https://github.com/Aiven-Open/klaw-docs/assets/943800/6b7a088e-eb4e-4901-8f94-05b26a0c6d32">

Note:  The error will list all findings for the use of "PostgreSQL" without the trademark. You need to add the `®` to the **first**  occurrence on the page. 

- update the usage to correct trademarking 

The `npm run spell:error` should be green before making a PR.

**Comment by morgoth9808** [comment]
Hey @programmiri  I would like to work on this issue please

**Comment by programmiri** [comment]
Hi @morgoth9808  I assigned you. Thank you! 🎉
