### ISSUE TITLE
Update docs to use the term "Klaw" correctly

### ISSUE THREAD

**Issue by programmiri** [Aiven-Open/klaw-docs#133]
Note: We already had an issue and PR for this, but to an error of our site with the github action, not all cases where fixed. 

# Description

"Klaw" should always be written capitalised when used in text.

Occurrences of other usages (e.g. "klaw" should be replaced with the correct one. 

In order to help find occurrences, we added a style rule in our Vale config (`.github/vale/styles/Klaw/branding-warning-temp.yml`) to _warn_ about this spellings.

## Todo:

- **cut** and past the line related to Klaw (`"(?i)klaw"`) from our temporary branding-warning config and add it to `.github/vale/styles/Klaw/branding.yml`
    - this will remove the rule from the mere warning and show it as error
- run `npm run spell:error`

This will give you a report of errors and help you find occurrences of the wrong use in the text.

The log will show you the file where the word was found as well as the line number, for example here:

<img width="708" alt="Screenshot 2023-09-28 at 13 26 44" src="https://github.com/Aiven-Open/klaw-docs/assets/943800/a5898430-96ab-4e44-b6f7-ed88e0e4634d">

- update the usage to correct branding in text in markdown files

## Note

This one will be more complex - or rather, a bit more manual checking for the context in which the error shows up.

-> we have cases in the doc where backticks to format code are missing, for example

klaw.clusterapi.access.base6

This should not be changed to use "klaw" in capitalised letters, but correctly put in backticks, then they are formatted as code correctly and Vale will not mark them as errors.

we also have cases where klaw shows up in file names in links, e.g. - [klaw-2.5.1.jar ⬇︎](https://github.com/Aiven-Open/klaw/releases/download/v2.5.1/klaw-2.5.1.jar)
In this case, too, the filename should be in backticks, not the spelling of Klaw changed.

🙏  So please keep an eye out for cases where Klaw is in lower-cases in for example wrongly formatted code lines. If it's relating for a file path for example, it does not need to be capitalised. Vale will not mark cases where "klaw" is formatted as code (in single or triple backticks `), but we may have usages of this without the correct formatting. In this cases, please fix the formatting (e.g. proper code). 

The `npm run spell:error` should be green before making a PR.

**Comment by Rawshansharma** [comment]
can i work on this issue ?

**Comment by programmiri** [comment]
Hi @Rawshansharma  sure! 

Just the note that this one will be more complex - or rather, a bit more manual checking for the context in which the error shows up. 

->  we have cases in the doc where backticks to format code are missing, for example 

> klaw.clusterapi.access.base6

This should not be changed to use "klaw" in capitalised letters, but correctly put in backticks, then they are formatted as code correctly and Vale will not mark them as errors. 

- we also have cases where klaw shows up in file names in links, e.g. `- [klaw-2.5.1.jar ⬇︎](https://github.com/Aiven-Open/klaw/releases/download/v2.5.1/klaw-2.5.1.jar)` 

In this case, too, the filename should be in backticks, not the spelling of Klaw changed.
