### ISSUE TITLE
Update copyright to 2024

### ISSUE THREAD

**Issue by aindriu-aiven** [Aiven-Open/klaw-docs#187]
Update copyright on documentation to 2024

**Comment by programmiri** [comment]
That's already done. 

@aindriu-aiven  just tagging you in case there's another occurrence that I didn't see.

<img width="671" alt="Screenshot 2024-07-16 at 08 27 54" src="https://github.com/user-attachments/assets/f0b89b72-7c41-44b5-a28a-1dfb0af7a58c">
