### ISSUE TITLE
Update docs to use the term "Klaw Cluster API" correctly

### ISSUE THREAD

**Issue by programmiri** [Aiven-Open/klaw-docs#99]
# Description

"Klaw Cluster API" should always be written in that way - capitalised and together. 

Occurrences of other usages (e.g. just "Cluster API" or "Klaw cluster API" etc. should be replaced with the correct one. 

In order to help find occurrences, we added a style rule in our Vale config (`branding-temp.xml`)

## Todo:

- cut and past the line related to Klaw Cluster API (`"(?<!Klaw )cluster api": Klaw Cluster API`) from our temporary branding-warning config and add it to `branding.yaml`

- run `npm run spell:error`

This will give you a report of errors and help you find occurrences of the wrong use in the text.

The log will show you the file where the word was found as well as the line number:

<img width="661" alt="Screenshot 2023-09-28 at 13 14 55" src="https://github.com/Aiven-Open/klaw-docs/assets/943800/a54b5235-6dfa-407a-a98e-a45c745e49d1">

- update the usage to correct branding in text in markdown files

The `npm run spell:error` should be green before making a PR.

**Comment by Devrishi-Dutta** [comment]
can I work on this issue?

**Comment by Rawshansharma** [comment]
can I work on this issue?

**Comment by programmiri** [comment]
Hi @Devrishi-Dutta  I'll assign this to you :) 

@Rawshansharma - I would ping you in case the issue gets stale.

**Comment by Devrishi-Dutta** [comment]
@programmiri I have created a pr for this issue . Please review and let me know if something is missing.

**Comment by programmiri** [comment]
Done with #125
